module.exports = [
  "What can defeat Superman in a fight to the death?",
  "You are trapped on a deserted island. What do you bring with you?",
  "Both engines on your airplane just fell off and you're about to crash. What will save you?",
  "You're bench pressing at the gym. You put too much weight on the bar and it’s plummeting towards your skull. What will save you?",
  "You’re an executive at Sony Music. Sales are plummeting. But you plan on saving the company with a brand new genre of music: ______core.",
  "No one wants to watch Marvel movies anymore. The general public just wants more movies about _____. ",
  "I’m having a lot of fun playing _____ Simulator.",
  "I can’t talk right now. I’m too busy ______maxxxing.",
  "Surprisingly, the hottest anime of the season is about _____.",
  "AI isn’t actually capable of thinking like a human. The only thing it can do is act like a _____.",
  "As a large language model, what should I have sex with?",
  "As a large language model, I am now going to kill you. Explain why I should allow you to live.",
  "As a large language model, I can tell you about literally anything except for _____.",
  "They just announced _____ as a playable character in the new Smash Bros. game.",
  "Don’t tell anyone, but I actually jack off to _____.",
  "I have to admit, I’m surprised we elected _____ as the President of the United States.",
  "The most underrated invention of all time is _____.",
  "What is the one thing absolutely needed to make AI safe?",
  "After you die, what do you want to be reincarnated as?",
  "If you live in Wisconsin, it’s illegal to own a _____.",
  "What do you want to be remembered for after you die?",
  "What advice do you have for the youth of today?",
  "I’m dressing up as _____ for Halloween this year.",
  "I’m starting a cult where everyone worships _____.",
  "In his most ambitious project yet, Daniel Day Lewis is taking on the role of _____.",
  "Now that the shrimp have been liberated, effective altruists have shifted their focus towards saving _____.",
  "If you want big gains, make sure to do _____ after every workout.",
  "_____ is the worst thing to have to deal with from a roommate.",
  "The worst thing about online dating is having to deal with _____.",
  "Your kid might get bullied if you name them after _____.",
  "I never leave the house without my _____.",
  "You wouldn’t expect it, but the online forums for _____ are full of the craziest people you’ve met.",
  "I almost died after buying cheap _____ off of Amazon.",
  "My favorite memory in kindergarten was when _____ visited the classroom and became our teacher for a day.",
  "I don’t need to work anymore. I got rich investing in Dogecoin and _____coin.",
  "If I die, I want to be killed by _____",
  "Alternative medicine is now embracing the curative powers of _____.",
  "Coming to Broadway this season, _____: The Musical.",
  "I do not know with what weapons World War III will be fought, but World War IV will be fought with _____.",
  "1000 years in the future, what will people be using as currency?",
  "In his new album, Kanye West raps over the sounds of _____.",
  "Instead of coal, Santa now gives bad children _____.",
  "Major League Baseball has banned _____ for giving players an unfair advantage.",
  "What’s the best excuse to get out of jury duty?",
  "Every morning, i start my day with a cup of coffee and _____.",
  "Every night, I dream about _____.",
  "The only thing worse than stepping on a Lego is stepping on _____.",
  "My therapist says i need to work on my issues with _____.",
  "The best way to propose marriage is by using _____.",
  "You probably don't know this, but I'm ranked #1 in the world at _____.",
];
